### PR TITLE
Correct vendoring of storage

### PR DESCRIPTION
**Pull request by smarterclayton**
Resets the github.com/docker/distribution/vendor directory to the minimal state for the PR.

### CODE REVIEW

**Comment by miminar** [comment]
@smarterclayton the process of picking up dependencies needs to be documented somewhere. Either in the `vendor/` directory or somewhere in top-level `docs/` directory. Also a comment in the  `bump(github.com/docker/distribution): Remove extra vendoring` refering at least to the README would be nice.

I'd like to automate this during the next distribution rebase.

**Comment by smarterclayton** [comment]
It's documented in the README in the vendor directory.

**Comment by smarterclayton** [comment]
I don't think we're going to solve this automatically - it's not
computationally tractable to find the minimal set of code that is needed to
different in packages.

**Comment by miminar** [comment]
> It's documented in the README in the vendor directory.

I'm sorry for my lament. I should have checked twice before blaming. Too many files I guess. The explanation looks good to me.

> I don't think we're going to solve this automatically

 The rebases are going to get tougher :cry:.

**Comment by smarterclayton** [comment]
Yeah, we do need to build more automation though to make the decision
making process obvious.

**Pull request closed without merging**
